export default {
    // 场景公共
    sceneBack: require("../assets/images/public/back.png"),
    scenejiantou: require("../assets/images/public/jiantou.png"),

    // 场景一素材
    scene1bj: require("../assets/images/scene-1/scene-bj.png"),
    bl: require("../assets/images/scene-1/bl.png"),
    fang: require("../assets/images/scene-1/fang.png"),
    guang: require("../assets/images/scene-1/guang.png"),
    ka: require("../assets/images/scene-1/ka.png"),
    ka1: require("../assets/images/scene-1/ka-1.png"),
    nf: require("../assets/images/scene-1/nf.png"),
    nfs: require("../assets/images/scene-1/nfs.png"),
    qc: require("../assets/images/scene-1/qc.png"),
    qy: require("../assets/images/scene-1/qy.png"),
    qyt: require("../assets/images/scene-1/qyt.png"),
    yp: require("../assets/images/scene-1/yp.png"),
    yp1: require("../assets/images/scene-1/yp-1.png"),
    ys: require("../assets/images/scene-1/ys.png"),
    ys1: require("../assets/images/scene-1/ys-1.png"),
    yw: require("../assets/images/scene-1/yw.png"),
    yzwj: require("../assets/images/scene-1/yzwj.png"),
    zp: require("../assets/images/scene-1/zp.png"),
    zp1: require("../assets/images/scene-1/zp-1.png"),
    zp2: require("../assets/images/scene-1/zp-2.png"),
    bw: require("../assets/images/scene-1/bw.png"),
    text: require("../assets/images/scene-1/text.png"),
    text1: require("../assets/images/scene-1/text1.png"),
    td: require("../assets/images/scene-1/td.png"),
    tddg: require("../assets/images/scene-1/tddg.png"),
    xk: require("../assets/images/scene-1/xk.png"),
    xy: require("../assets/images/scene-1/xy.png"),
    yhg: require("../assets/images/scene-1/yhg.png"),
    rw: require("../assets/images/scene-1/rw.png"),

    // 场景二素材
    scene2bj: require("../assets/images/scene-2/bj.png"),
    scene2dz: require("../assets/images/scene-2/duanzan.png"),
    scene2zx: require("../assets/images/scene-2/zenxi.png"),
    scene2chihe: require("../assets/images/scene-2/chihe.png"),
    scene2rensheng: require("../assets/images/scene-2/rensheng.png"),
    scene2dengguang2: require("../assets/images/scene-2/dengguang2.png"),
    scene2dengguang1: require("../assets/images/scene-2/dengguang1.png"),
    scene2xinlige: require("../assets/images/scene-2/xinlige.png"),
    scene2shuihoushouru: require("../assets/images/scene-2/shuihoushouru.png"),
    scene2jiupingshou: require("../assets/images/scene-2/jiupingshou.png"),
    scene2pijiuyeti: require("../assets/images/scene-2/pijiuyeti.png"),
    scene2pijiu: require("../assets/images/scene-2/pijiu.png"),
    scene2jiubeishou: require("../assets/images/scene-2/jiubeishou.png"),
    scene2pijiubei: require("../assets/images/scene-2/pijiupei.png"),
    scene2shou: require("../assets/images/scene-2/zuoshou.png"),
    scene2canchedengguang: require("../assets/images/scene-2/canchedengguang.png"),


    // 场景三素材
    scene3bj: require("../assets/images/scene-3/bj.png"),
    scene3topren: require("../assets/images/scene-3/topren.png"),
    scene3topbj: require("../assets/images/scene-3/topbj.png"),
    scene3zugexian: require("../assets/images/scene-3/geduan.png"),
    scene3kulian: require("../assets/images/scene-3/jusang.png"),
    scene3shouru: require("../assets/images/scene-3/shouru.png"),
    scene3xiaolian: require("../assets/images/scene-3/dengyan.png"),
    scene3gantan: require("../assets/images/scene-3/gantan.png"),
    scene3chaoren: require("../assets/images/scene-3/chaoren.png"),
    scene3pingmu: require("../assets/images/scene-3/pingmu.png"),
    scene3botren: require("../assets/images/scene-3/botren.png"),
    scene3Text: require("../assets/images/scene-3/text.png"),
    scene3Text1: require("../assets/images/scene-3/text1.png"),
    scene3Text2: require("../assets/images/scene-3/text2.png"),
    scene3Text3: require("../assets/images/scene-3/text3.png"),
    scene3qiuzhu: require("../assets/images/scene-3/qiuzhu.png"),
    scene3zhuqu: require("../assets/images/scene-3/zhiqu.png"),
    scene3baolei: require("../assets/images/scene-3/baolei.png"),
    scene3feicai: require("../assets/images/scene-3/feicai.png"),
    scene3del1: require("../assets/images/scene-3/del.png"),
    scene3del2: require("../assets/images/scene-3/del.png"),
    scene3del3: require("../assets/images/scene-3/del.png"),
    scene3xiaoxi: require("../assets/images/scene-3/xianxi.png"),

    // 场景四素材
    scene4bj: require("../assets/images/scene-4/bj.png"),
    scene4bicai: require("../assets/images/scene-4/bicai.png"),
    scene4botcafei: require("../assets/images/scene-4/botcafei.png"),
    scene4cafeiqi1: require("../assets/images/scene-4/cafeiqi.png"),
    scene4cafeiqi2: require("../assets/images/scene-4/cafeiqi.png"),
    scene4botnan: require("../assets/images/scene-4/botnan.png"),
    scene4botnv: require("../assets/images/scene-4/botnv.png"),
    scene4bottable: require("../assets/images/scene-4/bottable.png"),
    scene4gebo: require("../assets/images/scene-4/gebo.png"),
    scene4jianzhu: require("../assets/images/scene-4/jianzhu.png"),
    scene4nan: require("../assets/images/scene-4/nan.png"),
    scene4nandunpan: require("../assets/images/scene-4/nandunpan.png"),
    scene4nv: require("../assets/images/scene-4/nv.png"),
    scene4nvkuijia: require("../assets/images/scene-4/nvkuijia.png"),
    scene4shoubizhezhao: require("../assets/images/scene-4/shoubizhezhao.png"),
    scene4text1: require("../assets/images/scene-4/text1.png"),
    scene4text2: require("../assets/images/scene-4/text2.png"),

    // 场景五素材
    //   scene5bj: require("../assets/images/scene-5/bj.png"),
    scene5table: require("../assets/images/scene-5/table.png"),
    scene5phone: require("../assets/images/scene-5/phone.png"),
    // scene5tipphone: require("../assets/images/scene-5/tipphone.png"),
    scene5tipphone: require("../assets/images/scene-5/tipphpne.png"),

    // 攻略主会场
    mainback: require("../assets/images/main/back.png"),
    mainhuikan: require("../assets/images/main/huikan.png"),
    mainbotbj: require("../assets/images/main/botbj.jpg"),
    mainbtn1: require("../assets/images/main/btn1.png"),
    mainbtn2: require("../assets/images/main/btn2.png"),
    mainjianbian: require("../assets/images/main/jianbian.png"),
    maintopbj: require("../assets/images/main/topbj.png"),

    mainddfgl_a: require("../assets/images/main/ddfgl_a@2x.png"),
    mainddfgl_b: require("../assets/images/main/ddfgl_b@2x.png"),
    mainddfgl_c: require("../assets/images/main/ddfgl_c@2x.png"),
    mainddfgl_d: require("../assets/images/main/ddfgl_d@2x.png"),

    mainptjs_a: require("../assets/images/main/ptjs_a@2x.png"),
    mainptjs_b: require("../assets/images/main/ptjs_b@2x.png"),

    mainxsfljs_a: require("../assets/images/main/xsfljs_a@2x.png"),
    mainxsfljs_b: require("../assets/images/main/xsfljs_b@2x.png"),
    mainxsfljs_c: require("../assets/images/main/xsfljs_c@2x.png"),
    mainxsfljs_d: require("../assets/images/main/xsfljs_d@2x.png"),
}
